spring.application.name=zavrsniBackend

spring.security.oauth2.client.registration.google.client-id=FAKE_IDE
spring.security.oauth2.client.registration.google.client-secret=FAKE_SECRET
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile, email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


jwt.token-validity-seconds=3600
jwt.base64-secret=FAKE_SECRET

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.platform=h2
logging.level.org.springframework.jdbc.core=DEBUG
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB